### ISSUE TITLE
handycalc22 작동법

### ISSUE THREAD

**Issue by PyJAV13** [Qone2/handycalc#4]
안녕하세요 설명하신대로 했는데 
Traceback (most recent call last):
  File "C:\Users\kms53\Desktop\handycalc-master\handycalc22\handycalc22.py", line 8, in <module>
    from click import click, key_click
  File "C:\Users\kms53\Desktop\handycalc-master\handycalc22\click.py", line 5, in <module>
    from handycalc22 import HandyCalc
  File "C:\Users\kms53\Desktop\handycalc-master\handycalc22\handycalc22.py", line 8, in <module>
    from click import click, key_click
ImportError: cannot import name 'click' from partially initialized module 'click' (most likely due to a circular import) (C:\Users\kms53\Desktop\handycalc-master\handycalc22\click.py)
이런 에러가 나옵니다.
혹시 그래서인데 하시는 걸 동영상이나 사진으로 보여주실수 있을까요?

**Comment by Qone2** [comment]
@PyJAV13 handycalc22폴더는 현재작업중인 폴더입니다. 그냥 handycalc-master 폴더의 handycalc22.py를 사용하시면 됩니다.
사실 master브렌치에 작업중인 내용을 올리면 안되는데 실수로 올리게됐습니다.

**Comment by PyJAV13** [comment]
제가 pyautogui를 설치하려고 하는데
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyautogui in c:\users\kms53\appdata\roaming\python\python310\site-packages (0.9.53)
Requirement already satisfied: PyTweening>=1.0.1 in c:\users\kms53\appdata\roaming\python\python310\site-packages (from pyautogui) (1.0.4)
Requirement already satisfied: pyscreeze>=0.1.21 in c:\users\kms53\appdata\roaming\python\python310\site-packages (from pyautogui) (0.1.28)
Requirement already satisfied: pymsgbox in c:\users\kms53\appdata\roaming\python\python310\site-packages (from pyautogui) (1.0.9)
Requirement already satisfied: mouseinfo in c:\users\kms53\appdata\roaming\python\python310\site-packages (from pyautogui) (0.1.3)
Requirement already satisfied: pygetwindow>=0.0.5 in c:\users\kms53\appdata\roaming\python\python310\site-packages (from pyautogui) (0.0.9)
Requirement already satisfied: pyrect in c:\users\kms53\appdata\roaming\python\python310\site-packages (from pygetwindow>=0.0.5->pyautogui) (0.2.0)
Requirement already satisfied: pyperclip in c:\users\kms53\appdata\roaming\python\python310\site-packages (from mouseinfo->pyautogui) (1.8.2)
이런문장이 뜨는데 설치가 된게 맞나요?

**Comment by PyJAV13** [comment]
네네 ㅠㅠ 맞게 설정했는데 안되네요
대전찾기부분까진 찾아가는데 그 이후 클릭을 안하네요 
뭐가 문제일까요?

**Comment by Qone2** [comment]
@PyJAV13 찾는다는 보장은 없지만 해당부분 스크린샷 롤아이디 가려서 여기에 올려주시면 봐드릴게요. 아이디 및 기타 개인사항 가려주시고, 여기 입력창에 드래그엔드랍 하시면 사진 올라갑니다.

**Comment by PyJAV13** [comment]
cmd가 안가려져도 저기서 계속 클릭도 안하고 반복하네요
![Uploading BA159926-8D74-4F85-A669-6E73A0795923.png…]()

**Comment by PyJAV13** [comment]
![8441F547-7B91-4419-A52C-49F74BA290D2](https://user-images.githubusercontent.com/103041130/161771930-c4c04143-c516-47e5-9536-19f7c9d8fedd.png)
가려지는것과 상관없이 저기까지가다 클릭을 안하고 다시 돌아오네요

**Comment by Qone2** [comment]
@PyJAV13 아이디를 가리기 위해 저렇게 했다는거죠? 클라이언트를 가리면 안돼요. 그리고 화면의 스크린캡쳐를 보내주셔야지 사진찍은걸 보내주면 제가 뭘 봐드릴 수가 없죠... 윈도우 기본프로그램인 `캡처 도구`로 캡쳐해봐요 캡쳐하고 편집으로 아이디 가릴 수도 있어요. 

그나저나 클릭만 안되는거면 사실 다른 스크린샷 보내주신다고 해결될 거 같지는 않네요....

구글링 해보니까 cmd를 관리자권한으로 실행하면 될 지도 몰라요. cmd를 우클릭하면 관리자권한으로 실행하는 메뉴 있어요

**Comment by PyJAV13** [comment]
![캡처](https://user-images.githubusercontent.com/103041130/161778072-6c54572d-7b37-4776-a2bd-465b66267f38.PNG)
이렇게 되있습니다. 그런데 클릭이 안되네요...

**Comment by Qone2** [comment]
@PyJAV13 관리자권한으로 실행도 해보셨나요?

**Comment by PyJAV13** [comment]
관리자권한으로 실행이 안돼요...

**Comment by Qone2** [comment]
@PyJAV13 그리고 스크린샷 보면 더블클릭으로 실행하신 것 처럼 보이는데 cmd창에서 실행해주세요.
윈도우 하단 검색에서 `cmd`라고 치면 `명령 프롬프트`프로그램이 뜨고 그걸 우클릭 눌러서 관리자권한으로 실행 해주시고, handyclac22.py 파일을 cmd창에 드래그앤드랍 해주시고 엔터 하면 실행됩니다.

**Comment by PyJAV13** [comment]
python: can't open file 'C:\\Users\\kms53\\handycalc22.py': [Errno 2] No such file or directory
파일을 찾지 못했다고 하네요;;;

**Comment by PyJAV13** [comment]
위에것은 해결했는데 이번엔 홈화면 인식에서 넘어가지를 않네요;;;

**Comment by Qone2** [comment]
@PyJAV13 그러면 정말 모르겠네요.... pyautogui를 업데이트 하거나
예전에 파이썬 3.9로 하면 잘 안됐던 경험이 있는데 3.8버전으로 한번 해보는건 어떨까요...

**Comment by Qone2** [comment]
그냥 exe파일로 딱 올려버리면 다운받았을때 윈도우 디펜더가 막아버리네요. 스스로 pyinstaller를 통해서 exe를 만들어서 해보는 방법도 있을거같아요

**Comment by PyJAV13** [comment]
exe 까지 만들어서 실행해본 결과 롤클라이언트만 켜지고 이후 cmd도 꺼지고 아무 실행이 안됩니다...

**Comment by Qone2** [comment]
@PyJAV13 아뇨 원래 계속 반복되는게 정상입니다.

**Comment by Qone2** [comment]
클라이언트 위치잡아주는 부분이 수정되어있으니 최신버전으로도 해보셔요

**Comment by PyJAV13** [comment]
원래 게임실행되고 챔피언안사고 아이템도 안먹는게 정상인가요? 가만히 있는게 정상작동 되는거죠?

**Comment by Qone2** [comment]
20초정도 기다리면 챔피언은 사요

**Comment by PyJAV13** [comment]
지금까지 아무것도 안사고 있으면 문제있는건가요?

**Comment by Qone2** [comment]
프롬프트에는 뭐라고 나오나요?

**Comment by PyJAV13** [comment]
알수없는상황
알수없는상황
계속나오다 무한로딩 이렇게 뜨네요

**Comment by Qone2** [comment]
인게임인식을 전혀 못하고있네요... 롤 인게임 해상도 1920x1080 맞고, 화면 오른쪽부분에 뭐 가리고 있는거 아니죠?

**Comment by PyJAV13** [comment]
네네 전혀가린거 없이 진행되고있습니다

**Comment by Qone2** [comment]
오... 그렇군요.. 네 그것까진 굳이 구현하지 않았습니다

**Comment by PyJAV13** [comment]
그럼 게임실행후 챔피언 사는 곳만 계속 클릭하고 아이템은 사용하지않고 파란색 구나 회색 구 안먹고 아이템 선택하는곳에서는 안움직이는게 잘 실행되고있는거죠?

**Comment by Qone2** [comment]
네네 맞아요

**Comment by PyJAV13** [comment]
와 감사합니다 드디어 성공했네요 ㅠㅠ
끝까지 설명해주셔서 감사합니다ㅠ

**Comment by Qone2** [comment]
네네 참 레벨업은 나중에 시간 지나면 할거고... 좀 더 지켜보셔요 무한순환이 되어야 성공이라...

**Comment by PyJAV13** [comment]
레벨업 버튼도 실행되나요?

**Comment by Qone2** [comment]
게임시간 15분정도 지나면 레벨업버튼도 누릅니다

**Comment by PyJAV13** [comment]
레벨업버튼까지는 안누르는것 같긴한데 시간이 오래 안지나서 그런것일수도 있겠네요
감사합니다 또 작동에 문제있으면 말씀드리겠습니다

**Comment by PyJAV13** [comment]
혹시 이거 미션끝냈을때 토큰얻는화면에서 넘어가는건 인식을 못하나요?
화면에서 확인을 누르지 않고 인식을 못하는거 같아서요

**Comment by Qone2** [comment]
혹시 그거 또 뜨면 스크린샷 따서 올려줄 수 있나요? 전 이거 안한지 오래돼서 그 화면을 못봐요. 조금이라도 짤리면 안되고 전체 풀샷을 찍어야해요 좌표의 픽셀값을 봐야해서

**Comment by PyJAV13** [comment]
네 다시 또 뜨면 스크린샷 찍어서 올려드릴게요

**Comment by Qone2** [comment]
한판더하기 버튼과 혼동하는 문제였네요. 해당문제 수정하였습니다.

**Comment by PyJAV13** [comment]
감사합니다
이번에 추가된 아이템분배 할때 마우스가 전체적으로
아이템있는곳보다 오른쪽에서 실행되어 잘 분배가 안되는데 이건 어떻게 고쳐야할까요?

**Comment by PyJAV13** [comment]
기본전투장 쓰니 잘되네요

**Comment by Qone2** [comment]
아 예 기본전투장 기준입니다. 다른걸 많이 안써봐서 위치가 다른줄을 몰랐네요. 아이템 분배에 관한건 game_start 함수의 아이템 분배라고 주석표시 해둔 부분을 참고하면 됩니다. 거기서 random.uniform 의 범위를 조정해주면 되요. 아이템 위치를 일정범위의 랜덤으로 지정해뒀는데, 생각해보니까 아이템 위치는 몇군데 고정이라 그 위치 기준으로 하면 되긴 하네요..
